mysql:
  host: 127.0.0.1
  port: 3306
  db: uu
  username: root
  password: 2333tv.top
  log_level: dev
  config: charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai
  maxIdleConns: 10
  maxOpenConns: 25

logger:
  level: info
  prefix: '[uu]'
  show-line: true
  log-in-console: true

server:
  host: "0.0.0.0"
  port: 3601
  env: release

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0

email:
  host: smtp.qq.com
  port: 465
  email: goods.monitor@foxmail.com
  password: dhjdghlbwspcbjcc

wechat:
  app_id: wx3d1432382a8d4fe6
  app_secret: a90a8199acbe78db81995c090b97fb13

steamDt:
  key: 67529e0760394b408d140185ea328820
